name: Simple Alt Life Action Test

on:
  workflow_dispatch:
    inputs:
      wallet_address:
        description: 'Test Wallet Address'
        required: true
        default: '0x1234567890123456789012345678901234567890'
      git_url:
        description: 'Test Repository'
        required: true
        default: 'test-project-url'

jobs:
  test-action:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Run Alt Life Action
        uses: ./
        id: alt_life_test
        with:
          wallet_address: ${{ github.event.inputs.wallet_address }}
          git_url: ${{ github.event.inputs.git_url }}
      
      - name: Display Result
        run: |
          echo "## Alt Life Action Result" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.alt_life_test.outputs.result }}" >> $GITHUB_STEP_SUMMARY